name: hodo
description: "todo list app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.3
  sqflite: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/icon/
    - assets/font/
    - assets/image/

  fonts:
    - family: Certificate
      fonts:
        - asset: assets/font/Certificate.ttf

    - family: PlusJakartaSans
      fonts:
        - asset: assets/font/PlusJakartaSans-Regular.ttf

    - family: ComicSansCustom
      fonts:
        - asset: assets/font/Comic Sans MS.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
